# Hypothesis Testing & Feature Exploration

In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import category_encoders as ce
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import ElasticNet
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

## Load Data

In [2]:
patterns = pd.read_pickle('preprocessed_patterns.pkl')

In [3]:
patterns = patterns.drop(columns=['pattern_id', 'projects_count', 'favorites_count', 'author_id', 'estimated_revenue', 'total_languages', 'yarn_ids'])

In [4]:
patterns.describe()

,queued_projects_count,yardage,previously_published_patterns,days_since_publication,projects_per_day,price_usd,days_since_previous_pattern
count,559308.000000,559308.000000,559308.000000,559308.000000,559308.000000,559308.000000,559308.000000
mean,28.099493,412.522251,105.490880,2506.304778,0.008950,5.339493,1440.806184
std,139.963785,1064.542127,277.811141,1619.530390,0.138536,2.325749,1437.530544
min,0.000000,0.000000,1.000000,33.000000,0.000000,0.001550,0.000000
25%,1.000000,0.000000,10.000000,1169.000000,0.000000,4.000000,306.000000
50%,4.000000,197.000000,31.000000,2261.000000,0.000591,5.000000,986.000000
75%,15.000000,550.000000,88.000000,3698.000000,0.003049,6.474820,2165.000000
max,16025.000000,428696.000000,5009.000000,6989.000000,55.542169,100.000000,6910.000000

## Prepare Data

In [ ]:
# Convert yarn_weight to numeric before scaling
patterns['yarn_weight'] = patterns['yarn_weight'].map({
	'Thread': 1,
	'Cobweb': 2,
	'Lace': 3,
	'Light Fingering': 4,
	'Fingering': 5,
	'Sport': 6,
	'DK': 7,
	'Worsted': 8,
	'Aran': 9,
	'Bulky': 10,
	'Super Bulky': 11,
	'Jumbo': 12
}).fillna(8.5)
# Will be log-transformed & scaled along with some very skewed features; so needs to be exponentialized for the log to return correctly
patterns['yarn_weight'] = np.exp(patterns['yarn_weight'])

# Get log of then scale non-dummy features
float_features = ['yarn_weight', 'queued_projects_count', 'yardage', 'previously_published_patterns', 'days_since_publication', 'projects_per_day', 'price_usd', 'days_since_previous_pattern']
for feature in float_features:
    patterns[feature] = np.log1p(patterns[feature])

scaler = StandardScaler()
patterns[float_features] = scaler.fit_transform(patterns[float_features])

# Drop outliers with generous threshold of 4 standard deviations
for feature in float_features:
	patterns = patterns[np.abs(patterns[feature]) <= 4]

In [6]:
# Rename has_uk_terminology and has_us_terminology to uk_terminology and us_terminology for clarity
patterns = patterns.rename(columns={'has_uk_terminology': 'uk_terminology', 'has_us_terminology': 'us_terminology'})

In [7]:
# Where craft == knitting, set new `knit` column to 1
patterns['knit'] = ((patterns['craft'] == 'Knitting')).astype(int)

# Drop redundant/unhelpful columns
patterns = patterns.drop(columns=['craft', 'attributes_', 'pattern_source_type_names_', 'queued_projects_count', 'pattern_author'])

In [8]:
# Create weight column to weigh more recent patterns more heavily, using an exponential decay function with half-life of 4 years
half_life = 1460
lambda_ = np.log(2) / half_life
patterns['weight'] = np.exp(-lambda_ * patterns['days_since_publication'])

patterns = patterns.drop(columns = ['days_since_publication'])

In [9]:
# Convert `season` values to lowercase
patterns['season'] = patterns['season'].str.lower()

# Convert `season` to dummy
patterns = pd.get_dummies(patterns, columns=['season'], drop_first=True)

In [10]:
# Set final_category to concatenated string of supercategory, category, subcategory, and babycategory (in that order) with underscores as separators
# Skip missing values when concatenating
patterns['final_category'] = patterns['supercategory'].fillna('') + '_' + patterns['category'].fillna('') + '_' + patterns['subcategory'].fillna('') + '_' + patterns['babycategory'].fillna('')
patterns['final_category'] = patterns['final_category'].str.strip('_')  # Remove leading underscore

patterns = patterns.drop(columns = ['supercategory', 'category', 'subcategory', 'babycategory'])

# final_category will be target-encoded after the dataset has been split into train/test/validate groups

In [11]:
patterns.tail()

,yarn_weight,is_clothing,created_at,uk_terminology,us_terminology,yardage,attributes_2-at-a-time,attributes_3-4-sleeve,attributes_3-dimensional,attributes_Intarsia,...,yarn_fiber_Wool,yarn_fiber_Yak,price_usd,days_since_previous_pattern,knit,weight,season_spring,season_summer,season_winter,final_category
801683,-1.545488,True,2023-07-19 05:24:58+00:00,False,False,0.680108,False,False,False,False,...,True,False,0.014430,0.220720,1,1.000303,False,True,False,Accessories_Feet / Legs_Socks_Mid-calf
801684,-1.072667,True,2022-12-02 08:20:23+00:00,False,False,0.209994,False,False,False,False,...,False,False,-0.462688,0.066870,1,1.000200,False,False,True,Accessories_Feet / Legs_Socks_Mid-calf
801686,-0.118863,True,2024-10-22 05:51:45+00:00,False,False,0.632024,False,False,False,False,...,True,False,-0.398464,0.437605,1,1.000614,False,False,False,Accessories_Feet / Legs_Socks_Mid-calf
801687,-0.118863,True,2022-03-08 11:21:23+00:00,False,False,0.761987,False,False,False,False,...,True,False,0.422640,-0.204388,1,1.000101,True,False,False,Clothing_Sweater_Cardigan
801688,-0.118863,True,2023-10-04 19:07:01+00:00,False,False,0.793284,False,False,False,False,...,False,False,0.820946,0.264382,1,1.000344,False,False,False,Clothing_Sweater_Pullover

## Hypothesis Testing

In [12]:
model = smf.ols(
	formula = 'projects_per_day ~ price_usd * knit',
	data = patterns
).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       projects_per_day   R-squared:                       0.065
Model:                            OLS   Adj. R-squared:                  0.065
Method:                 Least Squares   F-statistic:                 1.289e+04
Date:                Wed, 15 Apr 2026   Prob (F-statistic):               0.00
Time:                        14:08:49   Log-Likelihood:            -1.7595e+05
No. Observations:              554747   AIC:                         3.519e+05
Df Residuals:                  554743   BIC:                         3.520e+05
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -0.1219      0.001   -171.497      0.000      -0.123      -0.121
price_usd          0.0188      0.001     27.715      0.000       0.018       0.020
knit               0.0986      0.001    106.187      0.000       0.097       0.100
price_usd:knit     0.0713      0.001     76.808      0.000       0.069       0.073
==============================================================================
Omnibus:                   627539.111   Durbin-Watson:                   1.318
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         53846441.884
Skew:                           6.016   Prob(JB):                         0.00
Kurtosis:                      49.741   Cond. No.                         3.23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

For the `price_usd:knit` interaction, the coefficient of 0.0713 with a p-value of 0.000 substantiates the hypothesis that knit patterns sell slightly better than crochet patterns as price increases.

In [13]:
# Get only most expensive 25% of patterns - this is equivalent to $6+ pre-scaling
expensive_patterns = patterns[patterns['price_usd'] >= 0.697828]

model = smf.ols(
	formula = 'projects_per_day ~ price_usd * knit',
	data = expensive_patterns
).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       projects_per_day   R-squared:                       0.036
Model:                            OLS   Adj. R-squared:                  0.036
Method:                 Least Squares   F-statistic:                     1570.
Date:                Wed, 15 Apr 2026   Prob (F-statistic):               0.00
Time:                        14:08:50   Log-Likelihood:                -96306.
No. Observations:              125986   AIC:                         1.926e+05
Df Residuals:                  125982   BIC:                         1.927e+05
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -0.0983      0.008    -13.075      0.000      -0.113      -0.084
price_usd          0.0124      0.006      2.158      0.031       0.001       0.024
knit               0.0817      0.009      8.994      0.000       0.064       0.099
price_usd:knit     0.1070      0.007     15.112      0.000       0.093       0.121
==============================================================================
Omnibus:                    99912.653   Durbin-Watson:                   1.226
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1932080.358
Skew:                           3.835   Prob(JB):                         0.00
Kurtosis:                      20.585   Cond. No.                         19.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Looking at only the most expensive 25% of patterns ($6+ USD), there is a stronger correlation between price increases and sales performance for knit patterns vs crochet. Within the more expensive segment of the market, the coefficient is 0.1070 with a p-value of 0.000.

In [14]:
# Hypothesis testing for impact of wool fiber
model = smf.ols(
	formula = 'projects_per_day ~ yarn_fiber_Wool',
	data = patterns
).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       projects_per_day   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.006
Method:                 Least Squares   F-statistic:                     3552.
Date:                Wed, 15 Apr 2026   Prob (F-statistic):               0.00
Time:                        14:08:50   Log-Likelihood:            -1.9287e+05
No. Observations:              554747   AIC:                         3.858e+05
Df Residuals:                  554745   BIC:                         3.858e+05
Df Model:                           1
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                  -0.0708      0.001   -138.800      0.000      -0.072      -0.070
yarn_fiber_Wool[T.True]     0.0702      0.001     59.602      0.000       0.068       0.072
==============================================================================
Omnibus:                   635350.710   Durbin-Watson:                   1.254
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         54499543.499
Skew:                           6.156   Prob(JB):                         0.00
Kurtosis:                      49.971   Cond. No.                         2.67
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

The coefficient of 0.0702 with a p-value of 0.000 indicates that use of wool yarn in a pattern does produce a slight increase in pattern sales vs non-wool yarns.

## Split Into Training, Testing, & Validation Sets

In [15]:
patterns = patterns.sort_values('created_at').reset_index(drop = True)

train = patterns[patterns['created_at'].dt.date < pd.to_datetime('2025-3-1').date()]
w = train['weight']
test = patterns[(patterns['created_at'].dt.date >= pd.to_datetime('2025-3-1').date()) & (patterns['created_at'].dt.date <= pd.to_datetime('2025-8-31').date())]
val = patterns[(patterns['created_at'].dt.date >= pd.to_datetime('2025-9-1').date()) & (patterns['created_at'].dt.date <= pd.to_datetime('2026-2-28').date())]

In [16]:
X_train = train.drop(columns= ['projects_per_day', 'created_at', 'weight'])
y_train = train['projects_per_day']

X_test = test.drop(columns= ['projects_per_day', 'created_at', 'weight'])
y_test = test['projects_per_day']

X_val = val.drop(columns= ['projects_per_day', 'created_at', 'weight'])
y_val = val['projects_per_day']

## Convert final_category to Target Encoding

In [17]:
# Convert final_category to target encoding
encoder = ce.CatBoostEncoder(cols = ['final_category'])
encoder.fit(X_train['final_category'], y_train)

X_train['final_category'] = encoder.transform(X_train['final_category'])
X_test['final_category'] = encoder.transform(X_test['final_category'])
X_val['final_category'] = encoder.transform(X_val['final_category'])

## Feature Selection

In [18]:
X_train.info(verbose = True)

<class 'pandas.DataFrame'>
RangeIndex: 512199 entries, 0 to 512198
Data columns (total 301 columns):
 #    Column                                   Dtype
---   ------                                   -----
 0    yarn_weight                              float64
 1    is_clothing                              bool
 2    uk_terminology                           bool
 3    us_terminology                           bool
 4    yardage                                  float64
 5    attributes_2-at-a-time                   bool
 6    attributes_3-4-sleeve                    bool
 7    attributes_3-dimensional                 bool
 8    attributes_Intarsia                      bool
 9    attributes_Shetland                      bool
 10   attributes_adaptive                      bool
 11   attributes_adult                         bool
 12   attributes_afterthought-heel             bool
 13   attributes_afterthought-pocket           bool
 14   attributes_aline                         bool
 15   attributes_amigurumi                     bool
 16   attributes_andean                        bool
 17   attributes_appliqued                     bool
 18   attributes_aran                          bool
 19   attributes_asymmetric                    bool
 20   attributes_baby                          bool
 21   attributes_backfastening                 bool
 22   attributes_ballet-neck                   bool
 23   attributes_bavarian                      bool
 24   attributes_beads                         bool
 25   attributes_bias                          bool
 26   attributes_boat-neck                     bool
 27   attributes_bobble-or-popcorn             bool
 28   attributes_bottom-up                     bool
 29   attributes_box-pleats                    bool
 30   attributes_bracelet-sleeve               bool
 31   attributes_braids-plaiting               bool
 32   attributes_brioche-tuck                  bool
 33   attributes_broomstick                    bool
 34   attributes_bruges                        bool
 35   attributes_bullion                       bool
 36   attributes_buttoned                      bool
 37   attributes_buttonholes                   bool
 38   attributes_cables                        bool
 39   attributes_cap-sleeve                    bool
 40   attributes_captioned-video               bool
 41   attributes_chart                         bool
 42   attributes_chevron                       bool
 43   attributes_child                         bool
 44   attributes_circle-shaped                 bool
 45   attributes_circular-yoke                 bool
 46   attributes_clones                        bool
 47   attributes_collar                        bool
 48   attributes_color-blind-accessible        bool
 49   attributes_contiguous                    bool
 50   attributes_convertible                   bool
 51   attributes_corrugated-ribbing            bool
 52   attributes_cowichan                      bool
 53   attributes_cowl-neck                     bool
 54   attributes_crescent-shape                bool
 55   attributes_crew-neck                     bool
 56   attributes_crocheted-edging              bool
 57   attributes_crohook                       bool
 58   attributes_cropped                       bool
 59   attributes_crotat                        bool
 60   attributes_cube-shaped                   bool
 61   attributes_cuffed-sleeve                 bool
 62   attributes_danish                        bool
 63   attributes_darts                         bool
 64   attributes_digital-audio                 bool
 65   attributes_digital-braille               bool
 66   attributes_doll-size                     bool
 67   attributes_dolman-sleeve                 bool
 68   attributes_doublebreasted                bool
 69   attributes_doubleknit                    bool
 70   attributes_drop-sleeve                   bool
 71   attributes_dropped-stitches              bool
 72   attributes_duplicate-stitch              bool
 73   attributes_dutch-heel                    bool
 74   attributes_elastic                       bool
 75   attributes_elbow-sleeve                  bool
 76   attributes_embroidery                    bool
 77   attributes_empire                        bool
 78   attributes_entrelac                      bool
 79   attributes_estonian                      bool
 80   attributes_eyelets                       bool
 81   attributes_facings                       bool
 82   attributes_fairisle                      bool
 83   attributes_faroese                       bool
 84   attributes_felted                        bool
 85   attributes_female                        bool
 86   attributes_filet-crochet                 bool
 87   attributes_finnish                       bool
 88   attributes_fitted                        bool
 89   attributes_flutter-sleeve                bool
 90   attributes_freeform                      bool
 91   attributes_fringe                        bool
 92   attributes_front-fastening               bool
 93   attributes_funnel-neck                   bool
 94   attributes_gathers                       bool
 95   attributes_granny-square                 bool
 96   attributes_guernsey                      bool
 97   attributes_gusset                        bool
 98   attributes_hairpin-crochet               bool
 99   attributes_halfcircle-shape              bool
 100  attributes_halter-neck                   bool
 101  attributes_heel-flap                     bool
 102  attributes_hems                          bool
 103  attributes_henley-neck                   bool
 104  attributes_hexagon                       bool
 105  attributes_hidden-pocket                 bool
 106  attributes_hood                          bool
 107  attributes_icelandic                     bool
 108  attributes_icord                         bool
 109  attributes_icord-edging                  bool
 110  attributes_illusion                      bool
 111  attributes_in-the-round                  bool
 112  attributes_irish                         bool
 113  attributes_irish-crochet                 bool
 114  attributes_keyhole-neck                  bool
 115  attributes_kitchener                     bool
 116  attributes_lace                          bool
 117  attributes_lace-edging                   bool
 118  attributes_latvian                       bool
 119  attributes_lined                         bool
 120  attributes_long-sleeve                   bool
 121  attributes_lovers                        bool
 122  attributes_low-vision                    bool
 123  attributes_machine-instructions          bool
 124  attributes_male                          bool
 125  attributes_mandarin                      bool
 126  attributes_maternity                     bool
 127  attributes_mature                        bool
 128  attributes_medical-device-access         bool
 129  attributes_medical-device-accessory      bool
 130  attributes_mesh                          bool
 131  attributes_miniature                     bool
 132  attributes_mobility-aid-accessory        bool
 133  attributes_mock-turtleneck               bool
 134  attributes_modified-drop-sleeve          bool
 135  attributes_modular                       bool
 136  attributes_moebius                       bool
 137  attributes_mosaic                        bool
 138  attributes_motifs                        bool
 139  attributes_nalgar-sleeve                 bool
 140  attributes_negative-ease                 bool
 141  attributes_newborn-size                  bool
 142  attributes_no-ease                       bool
 143  attributes_norwegian                     bool
 144  attributes_noshaping                     bool
 145  attributes_notched                       bool
 146  attributes_octagon                       bool
 147  attributes_one-piece                     bool
 148  attributes_orenburg                      bool
 149  attributes_other-accessibility           bool
 150  attributes_other-colorwork               bool
 151  attributes_other-edging                  bool
 152  attributes_other-heel                    bool
 153  attributes_other-toe                     bool
 154  attributes_oval                          bool
 155  attributes_oversized                     bool
 156  attributes_patch-pocket                  bool
 157  attributes_pattern-recipe                bool
 158  attributes_pentagon-shape                bool
 159  attributes_peplum                        bool
 160  attributes_peterpan                      bool
 161  attributes_petite                        bool
 162  attributes_phototutorial                 bool
 163  attributes_picots                        bool
 164  attributes_pineapple                     bool
 165  attributes_pleated                       bool
 166  attributes_plus                          bool
 167  attributes_pockets                       bool
 168  attributes_positive-ease                 bool
 169  attributes_post-stitch                   bool
 170  attributes_preemie                       bool
 171  attributes_provisional                   bool
 172  attributes_puffed-sleeve                 bool
 173  attributes_pyramid                       bool
 174  attributes_racerback                     bool
 175  attributes_raglan-sleeve                 bool
 176  attributes_rectangle                     bool
 177  attributes_reversible                    bool
 178  attributes_ribbed                        bool
 179  attributes_ripple                        bool
 180  attributes_rolled                        bool
 181  attributes_ruffles                       bool
 182  attributes_saddle-shoulder               bool
 183  attributes_sami                          bool
 184  attributes_schematic                     bool
 185  attributes_scoop-neck                    bool
 186  attributes_screen-reader                 bool
 187  attributes_seamed                        bool
 188  attributes_seamed-sock                   bool
 189  attributes_seamless                      bool
 190  attributes_selvedge                      bool
 191  attributes_set-in-pocket                 bool
 192  attributes_set-in-sleeve                 bool
 193  attributes_shaped-arches                 bool
 194  attributes_shawl                         bool
 195  attributes_shirt-collar                  bool
 196  attributes_short-row-heel                bool
 197  attributes_short-row-toe                 bool
 198  attributes_short-rows                    bool
 199  attributes_short-sleeve                  bool
 200  attributes_shoulder-fastening            bool
 201  attributes_sideways                      bool
 202  attributes_single-breasted               bool
 203  attributes_sleeveless                    bool
 204  attributes_sleeves                       bool
 205  attributes_slip-stitch                   bool
 206  attributes_slipped-stitches              bool
 207  attributes_smocked                       bool
 208  attributes_snaps                         bool
 209  attributes_sphere-shaped                 bool
 210  attributes_square                        bool
 211  attributes_square-neck                   bool
 212  attributes_star-shaped                   bool
 213  attributes_star-toe                      bool
 214  attributes_start-in-middle               bool
 215  attributes_steeks                        bool
 216  attributes_straight                      bool
 217  attributes_stranded                      bool
 218  attributes_stripes                       bool
 219  attributes_stripes-colorwork             bool
 220  attributes_surface-crochet               bool
 221  attributes_surplice-neck                 bool
 222  attributes_swedish                       bool
 223  attributes_sweetheart-neck               bool
 224  attributes_swing                         bool
 225  attributes_tall                          bool
 226  attributes_tapestry-crochet              bool
 227  attributes_tassel                        bool
 228  attributes_teen                          bool
 229  attributes_textured                      bool
 230  attributes_therapy-aid                   bool
 231  attributes_three-needle-bind             bool
 232  attributes_thrums                        bool
 233  attributes_tied                          bool
 234  attributes_toddler                       bool
 235  attributes_toe-up                        bool
 236  attributes_top-cuff-down                 bool
 237  attributes_top-down                      bool
 238  attributes_triangle-shaped               bool
 239  attributes_tubular-pocket                bool
 240  attributes_tulip-sleeve                  bool
 241  attributes_tunisian                      bool
 242  attributes_turkish                       bool
 243  attributes_turtleneck                    bool
 244  attributes_twined                        bool
 245  attributes_twisted-stitches              bool
 246  attributes_unisex                        bool
 247  attributes_v-neck                        bool
 248  attributes_video-tutorial                bool
 249  attributes_waist                         bool
 250  attributes_wide-toe                      bool
 251  attributes_worked-flat                   bool
 252  attributes_wrap                          bool
 253  attributes_written-pattern               bool
 254  attributes_zipper                        bool
 255  pattern_source_type_names_App            bool
 256  pattern_source_type_names_Book           bool
 257  pattern_source_type_names_Magazine       bool
 258  pattern_source_type_names_Pamphlet       bool
 259  pattern_source_type_names_Ravelry Store  bool
 260  pattern_source_type_names_Website        bool
 261  pattern_source_type_names_Webzine        bool
 262  pattern_source_type_names_eBook          bool
 263  previously_published_patterns            float64
 264  free_patterns                            bool
 265  animal_fiber                             bool
 266  synthetic_fiber                          bool
 267  vegetable_fiber                          bool
 268  yarn_fiber_Acrylic                       bool
 269  yarn_fiber_Alpaca                        bool
 270  yarn_fiber_Angora                        bool
 271  yarn_fiber_Bamboo                        bool
 272  yarn_fiber_Bison                         bool
 273  yarn_fiber_Camel                         bool
 274  yarn_fiber_Cashmere                      bool
 275  yarn_fiber_Cotton                        bool
 276  yarn_fiber_Hemp                          bool
 277  yarn_fiber_Linen                         bool
 278  yarn_fiber_Llama                         bool
 279  yarn_fiber_Merino                        bool
 280  yarn_fiber_Metallic                      bool
 281  yarn_fiber_Microfiber                    bool
 282  yarn_fiber_Mohair                        bool
 283  yarn_fiber_Nylon                         bool
 284  yarn_fiber_Other                         bool
 285  yarn_fiber_Plant fiber                   bool
 286  yarn_fiber_Polyester                     bool
 287  yarn_fiber_Qiviut                        bool
 288  yarn_fiber_Rayon                         bool
 289  yarn_fiber_Silk                          bool
 290  yarn_fiber_Soy                           bool
 291  yarn_fiber_Tencel                        bool
 292  yarn_fiber_Wool                          bool
 293  yarn_fiber_Yak                           bool
 294  price_usd                                float64
 295  days_since_previous_pattern              float64
 296  knit                                     int64
 297  season_spring                            bool
 298  season_summer                            bool
 299  season_winter                            bool
 300  final_category                           float64
dtypes: bool(294), float64(6), int64(1)
memory usage: 171.0 MB

### Polynomial Linear Regression

In [19]:
numeric_cols = [
	'yarn_weight',
	'yardage',
	'price_usd',
	'days_since_previous_pattern',
	'final_category'
]

preprocess = ColumnTransformer(
	transformers = [
		('poly', PolynomialFeatures(degree = 2, include_bias = False), numeric_cols),
		('pass', 'passthrough', [c for c in X_train.columns if c not in numeric_cols])
	]
)

In [20]:
pipe = Pipeline([
	('prep', preprocess),
	('model', ElasticNet())
])

pipe.fit(X_train, y_train, model__sample_weight = w)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('poly',
                                                  PolynomialFeatures(include_bias=False),
                                                  ['yarn_weight', 'yardage',
                                                   'price_usd',
                                                   'days_since_previous_pattern',
                                                   'final_category']),
                                                 ('pass', 'passthrough',
                                                  ['is_clothing',
                                                   'uk_terminology',
                                                   'us_terminology',
                                                   'attributes_2-at-a-time',
                                                   'attributes_3-4-sleeve',
                                                   'attributes_3-dimensional',
                                                   'attributes_In...
                                                   'attributes_aran',
                                                   'attributes_asymmetric',
                                                   'attributes_baby',
                                                   'attributes_backfastening',
                                                   'attributes_ballet-neck',
                                                   'attributes_bavarian',
                                                   'attributes_beads',
                                                   'attributes_bias',
                                                   'attributes_boat-neck',
                                                   'attributes_bobble-or-popcorn',
                                                   'attributes_bottom-up',
                                                   'attributes_box-pleats',
                                                   'attributes_bracelet-sleeve',
                                                   'attributes_braids-plaiting', ...])])),
                ('model', ElasticNet())])

In [21]:
pipe.score(X_test, y_test)

-0.04169546677813685

Performs very slightly better (less bad) than ElasticNet regression without polynomial features.

### Random Forest

In [22]:
# Parameters have been reduced to prevent kernel crashing
rf = RandomForestRegressor(
    n_estimators=50,      # Reduce from default 100
    max_depth=15,         # Limit tree depth
    n_jobs=1,             # Use single core instead of all cores
    verbose=0,
    random_state=42026
)

rf.fit(X_train, y_train, sample_weight = w)

rf.score(X_test, y_test)

0.19144260423515336

This one is performing slightly better than a null model! Let's check the feature importances.

In [23]:
# Just the top ones
for score, name in zip(rf.feature_importances_, X_train.columns):
	if score >= 0.01:
		print(round(score, 2), name)

0.02 yarn_weight
0.05 yardage
0.01 attributes_positive-ease
0.04 attributes_top-down
0.01 attributes_video-tutorial
0.01 pattern_source_type_names_Book
0.06 previously_published_patterns
0.02 yarn_fiber_Merino
0.17 price_usd
0.08 days_since_previous_pattern
0.01 knit
0.05 final_category

In [24]:
# All feature importances
for score, name in zip(rf.feature_importances_, X_train.columns):
	print(round(score, 4), name)

0.0247 yarn_weight
0.0028 is_clothing
0.0009 uk_terminology
0.0005 us_terminology
0.0485 yardage
0.0005 attributes_2-at-a-time
0.0009 attributes_3-4-sleeve
0.0014 attributes_3-dimensional
0.0012 attributes_Intarsia
0.0019 attributes_Shetland
0.0001 attributes_adaptive
0.0042 attributes_adult
0.0016 attributes_afterthought-heel
0.0013 attributes_afterthought-pocket
0.0011 attributes_aline
0.0019 attributes_amigurumi
0.0003 attributes_andean
0.0005 attributes_appliqued
0.0006 attributes_aran
0.0033 attributes_asymmetric
0.0027 attributes_baby
0.0007 attributes_backfastening
0.0007 attributes_ballet-neck
0.0002 attributes_bavarian
0.0028 attributes_beads
0.0052 attributes_bias
0.0006 attributes_boat-neck
0.0025 attributes_bobble-or-popcorn
0.003 attributes_bottom-up
0.0004 attributes_box-pleats
0.0014 attributes_bracelet-sleeve
0.0006 attributes_braids-plaiting
0.0027 attributes_brioche-tuck
0.0 attributes_broomstick
0.0 attributes_bruges
0.0 attributes_bullion
0.0016 attributes_buttoned
0.0017 attributes_buttonholes
0.0031 attributes_cables
0.0007 attributes_cap-sleeve
0.0035 attributes_captioned-video
0.005 attributes_chart
0.0026 attributes_chevron
0.0029 attributes_child
0.001 attributes_circle-shaped
0.0016 attributes_circular-yoke
0.0 attributes_clones
0.0013 attributes_collar
0.0012 attributes_color-blind-accessible
0.0011 attributes_contiguous
0.0008 attributes_convertible
0.0009 attributes_corrugated-ribbing
0.0 attributes_cowichan
0.0006 attributes_cowl-neck
0.0016 attributes_crescent-shape
0.0022 attributes_crew-neck
0.0005 attributes_crocheted-edging
0.0 attributes_crohook
0.0023 attributes_cropped
0.0 attributes_crotat
0.0 attributes_cube-shaped
0.0005 attributes_cuffed-sleeve
0.0008 attributes_danish
0.0012 attributes_darts
0.0 attributes_digital-audio
0.0 attributes_digital-braille
0.0005 attributes_doll-size
0.0007 attributes_dolman-sleeve
0.0005 attributes_doublebreasted
0.0019 attributes_doubleknit
0.002 attributes_drop-sleeve
0.0005 attributes_dropped-stitches
0.0006 attributes_duplicate-stitch
0.0004 attributes_dutch-heel
0.0012 attributes_elastic
0.0004 attributes_elbow-sleeve
0.0009 attributes_embroidery
0.0003 attributes_empire
0.0 attributes_entrelac
0.0005 attributes_estonian
0.0037 attributes_eyelets
0.0009 attributes_facings
0.0015 attributes_fairisle
0.0001 attributes_faroese
0.0001 attributes_felted
0.0035 attributes_female
0.0001 attributes_filet-crochet
0.0002 attributes_finnish
0.0021 attributes_fitted
0.0 attributes_flutter-sleeve
0.0 attributes_freeform
0.0007 attributes_fringe
0.0009 attributes_front-fastening
0.0009 attributes_funnel-neck
0.0005 attributes_gathers
0.0007 attributes_granny-square
0.0 attributes_guernsey
0.0019 attributes_gusset
0.0 attributes_hairpin-crochet
0.0014 attributes_halfcircle-shape
0.0 attributes_halter-neck
0.0029 attributes_heel-flap
0.0007 attributes_hems
0.0008 attributes_henley-neck
0.0008 attributes_hexagon
0.0005 attributes_hidden-pocket
0.0015 attributes_hood
0.001 attributes_icelandic
0.0035 attributes_icord
0.0027 attributes_icord-edging
0.0001 attributes_illusion
0.0097 attributes_in-the-round
0.0001 attributes_irish
0.0 attributes_irish-crochet
0.0 attributes_keyhole-neck
0.003 attributes_kitchener
0.0036 attributes_lace
0.0009 attributes_lace-edging
0.0007 attributes_latvian
0.0003 attributes_lined
0.0014 attributes_long-sleeve
0.0 attributes_lovers
0.0011 attributes_low-vision
0.0 attributes_machine-instructions
0.0037 attributes_male
0.0 attributes_mandarin
0.0001 attributes_maternity
0.0002 attributes_mature
0.0 attributes_medical-device-access
0.0 attributes_medical-device-accessory
0.0019 attributes_mesh
0.0003 attributes_miniature
0.0 attributes_mobility-aid-accessory
0.0012 attributes_mock-turtleneck
0.0008 attributes_modified-drop-sleeve
0.0021 attributes_modular
0.0003 attributes_moebius
0.0032 attributes_mosaic
0.0008 attributes_motifs
0.0 attributes_nalgar-sleeve
0.0041 attributes_negative-ease
0.002 attributes_newborn-size
0.0018 attributes_no-ease
0.0013 attributes_norwegian
0.0007 attributes_noshaping
0.0001 attributes_notched
0.0002 attributes_octagon
0.0068 attributes_one-piece
0.0002 attributes_orenburg
0.0 attributes_other-accessibility
0.0017 attributes_other-colorwork
0.0012 attributes_other-edging
0.0011 attributes_other-heel
0.0024 attributes_other-toe
0.0003 attributes_oval
0.0018 attributes_oversized
0.0007 attributes_patch-pocket
0.001 attributes_pattern-recipe
0.0001 attributes_pentagon-shape
0.0001 attributes_peplum
0.0 attributes_peterpan
0.0017 attributes_petite
0.0032 attributes_phototutorial
0.0015 attributes_picots
0.0002 attributes_pineapple
0.0004 attributes_pleated
0.0028 attributes_plus
0.0008 attributes_pockets
0.0112 attributes_positive-ease
0.0008 attributes_post-stitch
0.0008 attributes_preemie
0.0018 attributes_provisional
0.0011 attributes_puffed-sleeve
0.0 attributes_pyramid
0.0003 attributes_racerback
0.0019 attributes_raglan-sleeve
0.0011 attributes_rectangle
0.0021 attributes_reversible
0.0047 attributes_ribbed
0.0006 attributes_ripple
0.0007 attributes_rolled
0.0008 attributes_ruffles
0.001 attributes_saddle-shoulder
0.0003 attributes_sami
0.0053 attributes_schematic
0.0011 attributes_scoop-neck
0.0007 attributes_screen-reader
0.0039 attributes_seamed
0.0001 attributes_seamed-sock
0.0066 attributes_seamless
0.0014 attributes_selvedge
0.001 attributes_set-in-pocket
0.0008 attributes_set-in-sleeve
0.0006 attributes_shaped-arches
0.0014 attributes_shawl
0.0009 attributes_shirt-collar
0.0014 attributes_short-row-heel
0.0013 attributes_short-row-toe
0.005 attributes_short-rows
0.0014 attributes_short-sleeve
0.0001 attributes_shoulder-fastening
0.0023 attributes_sideways
0.0012 attributes_single-breasted
0.0012 attributes_sleeveless
0.0013 attributes_sleeves
0.0003 attributes_slip-stitch
0.0042 attributes_slipped-stitches
0.0013 attributes_smocked
0.0009 attributes_snaps
0.0002 attributes_sphere-shaped
0.0015 attributes_square
0.0012 attributes_square-neck
0.0005 attributes_star-shaped
0.0006 attributes_star-toe
0.0001 attributes_start-in-middle
0.0008 attributes_steeks
0.0016 attributes_straight
0.0053 attributes_stranded
0.0019 attributes_stripes
0.0041 attributes_stripes-colorwork
0.0007 attributes_surface-crochet
0.0005 attributes_surplice-neck
0.0002 attributes_swedish
0.0001 attributes_sweetheart-neck
0.0005 attributes_swing
0.001 attributes_tall
0.0002 attributes_tapestry-crochet
0.0009 attributes_tassel
0.0047 attributes_teen
0.0058 attributes_textured
0.0002 attributes_therapy-aid
0.0019 attributes_three-needle-bind
0.0003 attributes_thrums
0.0007 attributes_tied
0.0023 attributes_toddler
0.0014 attributes_toe-up
0.0051 attributes_top-cuff-down
0.0446 attributes_top-down
0.0033 attributes_triangle-shaped
0.0004 attributes_tubular-pocket
0.0 attributes_tulip-sleeve
0.0001 attributes_tunisian
0.0 attributes_turkish
0.0014 attributes_turtleneck
0.0003 attributes_twined
0.0041 attributes_twisted-stitches
0.0086 attributes_unisex
0.0016 attributes_v-neck
0.0126 attributes_video-tutorial
0.001 attributes_waist
0.0013 attributes_wide-toe
0.0049 attributes_worked-flat
0.0011 attributes_wrap
0.0062 attributes_written-pattern
0.0006 attributes_zipper
0.0001 pattern_source_type_names_App
0.012 pattern_source_type_names_Book
0.0025 pattern_source_type_names_Magazine
0.0033 pattern_source_type_names_Pamphlet
0.0043 pattern_source_type_names_Ravelry Store
0.0053 pattern_source_type_names_Website
0.0029 pattern_source_type_names_Webzine
0.007 pattern_source_type_names_eBook
0.0629 previously_published_patterns
0.007 free_patterns
0.0042 animal_fiber
0.0024 synthetic_fiber
0.0015 vegetable_fiber
0.0028 yarn_fiber_Acrylic
0.0039 yarn_fiber_Alpaca
0.0006 yarn_fiber_Angora
0.0012 yarn_fiber_Bamboo
0.0002 yarn_fiber_Bison
0.002 yarn_fiber_Camel
0.0045 yarn_fiber_Cashmere
0.0015 yarn_fiber_Cotton
0.0005 yarn_fiber_Hemp
0.0025 yarn_fiber_Linen
0.0012 yarn_fiber_Llama
0.0246 yarn_fiber_Merino
0.0006 yarn_fiber_Metallic
0.0008 yarn_fiber_Microfiber
0.0041 yarn_fiber_Mohair
0.0027 yarn_fiber_Nylon
0.0018 yarn_fiber_Other
0.0009 yarn_fiber_Plant fiber
0.0008 yarn_fiber_Polyester
0.0 yarn_fiber_Qiviut
0.0009 yarn_fiber_Rayon
0.0043 yarn_fiber_Silk
0.0005 yarn_fiber_Soy
0.002 yarn_fiber_Tencel
0.0048 yarn_fiber_Wool
0.0022 yarn_fiber_Yak
0.1698 price_usd
0.0787 days_since_previous_pattern
0.014 knit
0.0045 season_spring
0.0046 season_summer
0.005 season_winter
0.0473 final_category